enum ErrorMessages {
  EMAIL_REQUIRED = "email is required",
  EMAIL_NOT_SENT = "email not sent",
  EMAIL_NOT_FOUND = "email not found",
  EMAIL_REQUIRED_AND_ACTIVE_CODE = "email is required and active code is required",
  ACTIVE_CODE_EXPIRED = "active code is expired",
  ACTIVE_CODE_NOT_MATCH = "activeCode is incorrect",
  REFRESH_TOKEN_REQUIRED = "refreshToken is required",
  REFRESH_TOKEN_IS_INVALID_OR_EXPIRED = "refreshToken is incorrect or expired",
  REFRESH_TOKEN_EXPIRED_PLEASE_LOGIN_AGAIN = "Refresh token has expired. Please login again.",
  INVALID_PAYLOAD = "Invalid token payload",
  USER_NOT_FOUND_OR_UNAUTHORIZED = "user not found or unauthorized",
  USER_TOKEN_IS_INVALID = "user token is invalid",
  UNAUTHORIZED_DEVICE_OR_ACCESS = "Unauthorized device or access",
  UNAUTHORIZED_ERROR = "no token provided or in-valid Bearer Key",
  ROLE_ERROR = `Forbidden: You must have the role to access this resource`,
  TOKEN_NOT_FOUND = "Token not found",
  INVALID_FILE_NAME = "Invalid file name",
  INVALID_CATEGORY_DATA = "Invalid category data",
  CATEGORY_NOT_FOUND = "Category not found",
  UNAUTHORIZED_ACCESS = "Unauthorized access",
CATEGORY_NOT_FOUND_OR_EALREADY_DELETED = "Category not found or already deleted",
NO_FILES_PROVIDED = "No files provided",
}
export default ErrorMessages;
